### ISSUE TITLE
[bug] `Memory.intel.targets` isn't being cleaned up

### ISSUE THREAD

**Issue by tedivm** [ScreepsQuorum/screeps-quorum#130]
This array seems to be growing without being cleaned up at all. Since it is regularly sorted this has an adverse affect on CPU beyond just the memory usage problems.

**Comment by tedivm** [comment]
It should be deleted [here](https://github.com/ScreepsQuorum/screeps-quorum/blob/master/src/extends/room/intel.js#L155) when the room is reprocessed.

**Comment by ViezeVingertjes** [comment]
Is this resolved or am i not seeing the edge case in here?

**Comment by tedivm** [comment]
It isn't resolved, but it's hard to see while we're in the the novice zone because it doesn't get a lot of targets.
