### ISSUE TITLE
[bug] Spook is using an obscene amount of CPU

### ISSUE THREAD

**Issue by tedivm** [ScreepsQuorum/screeps-quorum#149]
<img width="1037" alt="screen shot 2017-10-18 at 3 17 54 pm" src="https://user-images.githubusercontent.com/121709/31745455-98ae2584-b417-11e7-93de-6aabc63ae95d.png">

**Comment by TheRealMaxion** [comment]
I'm thinking the problem is probably in the Room.getScoutTarget function.

**Comment by TheRealMaxion** [comment]
....yes, because intel.targets is not getting cleaned up, spooks will keep costing more and more cpu.
