### ISSUE TITLE
[bug] Creeps crash sometimes and don't recover.

### ISSUE THREAD

**Issue by ViezeVingertjes** [ScreepsQuorum/screeps-quorum#156]
I've observed a creep crashing multiple times. No error's visible in the console, yet the creep stops doing his job and never recovers. It solves itself when the creep dies, but that's not the expected behavior.

Types i observed this with is: Miner & Hauler. In the miners case it was stuck on top of a container and stayed there, blocking other miners. In the case of the haulers (multiple), they were waiting next to a fully filled spawn, but not continued doing anything after the spawn was empty.

**Comment by lurr** [comment]
Currently imagining a creep driving a car and crashing, then recovering in the hospital.

**Comment by tedivm** [comment]
Was this after an upgrade? We changed the cluster naming scheme recently, so if you upgraded to the new scheme all the existing creeps before the upgrade would no longer be controlled.

**Comment by ViezeVingertjes** [comment]
I have setup auto deploy after PR #144, if that merge happened after that, it might be the case.

**Comment by ViezeVingertjes** [comment]
Just witnessed it again, it seems the program stops running at some point, in this case it was a starting room and the fillers stopped. Which automatically means the end of the room, unless the spawn fills up over time and it's lucky enough to spawn a filler.

**Comment by tedivm** [comment]
Has this come up again?

**Comment by Raggaer** [comment]
I been looking at my changes, I made some changes to `city.js`, those changes caused a syntax error, I uploaded a fix and the creeps died.

**Comment by Raggaer** [comment]
That could be the case then, thanks
