### ISSUE TITLE
[bug] Bots don't work anymore

### ISSUE THREAD

**Issue by duckymirror** [ScreepsQuorum/screeps-quorum#400]
The bots on this project are not doing anything anymore. The gitconsensus bot doesn't mark or merge any pull requests. ScreepsAutoSpawner doesn't execute a respawn. The official Quorum bot has been out of rooms for days.

**Comment by semperrabbit** [comment]
this was already identified to the host 2 days ago. he's busy irl, but he said he'd take a look at it when he could...

**Comment by duckymirror** [comment]
I'll leave this issue open. Information on this can be posted here.

**Comment by tedivm** [comment]
Github changed the response to some of the API calls and this broke the github python client I was using. Upgrading the library resolved that problem.

Still need to look at why the autospawner isn't working through.

**Comment by duckymirror** [comment]
Quorum is here again so I'm closing this.
