### ISSUE TITLE
Bad condition in extends/creep/movement.js

### ISSUE THREAD

**Issue by JeremyGagnier** [ScreepsQuorum/screeps-quorum#403]
See #401 for fix. Tried to get +1's without success, so this is to document this bug.

**Comment by duckymirror** [comment]
I think we have a bigger problem here. In the `if` part it sets `moveToOpts.avoidHostileRooms` to `true` but it is never used. I might be wrong but `avoidHostileRooms` appears exactly three times in the file:
1. To set the default value
2. To check whether it's `true` and if it is not
3. to set it to true in this `if` block.

The Screeps documentation doesn't contain anything about `avoidHostileRooms` at all. So probably it would be best to get rid of this option completely.

**Comment by mebays** [comment]
> I think we have a bigger problem here. In the `if` part it sets `moveToOpts.avoidHostileRooms` to `true` but it is never used. I might be wrong but `avoidHostileRooms` appears exactly three times in the file:
> 
>     1. To set the default value
> 
>     2. To check whether it's `true` and if it is not
> 
>     3. to set it to true in this `if` block.
> 
> 
> The Screeps documentation doesn't contain anything about `avoidHostileRooms` at all. So probably it would be best to get rid of this option completely.

Just a heads up avoidHostileRooms gets passed in the qlib.map.findRoute function. Which uses logic to determine if the creep should travel to a HostileRoom or not depending on the score. The PATH_WEIGHT_NEUTRAL constant is 2 so any score less than 2 will return a score. But if we get a score higher than 2 and it is specified that the creep should travel there then it can. 

The default can also be over written by passing options to the travelTo function (i.e. creep.travelTo(new RoomPosition(25, 25, <room>), {avoidHostileRooms: true}) 

If you get rid of the option then your never travel to a room that has a hostile weight which you may want to be able to do at some point. 

@JeremyGagnier if you open the PR for the fix I'd be happy to help with a +1 for you.

**Comment by duckymirror** [comment]
> 
> 
> > I think we have a bigger problem here. In the `if` part it sets `moveToOpts.avoidHostileRooms` to `true` but it is never used. I might be wrong but `avoidHostileRooms` appears exactly three times in the file:
> > ```
> > 1. To set the default value
> > 
> > 2. To check whether it's `true` and if it is not
> > 
> > 3. to set it to true in this `if` block.
> > ```
> > The Screeps documentation doesn't contain anything about `avoidHostileRooms` at all. So probably it would be best to get rid of this option completely.
> 
> Just a heads up avoidHostileRooms gets passed in the qlib.map.findRoute function. Which uses logic to determine if the creep should travel to a HostileRoom or not depending on the score. The PATH_WEIGHT_NEUTRAL constant is 2 so any score less than 2 will return a score. But if we get a score higher than 2 and it is specified that the creep should travel there then it can.
> 
> The default can also be over written by passing options to the travelTo function (i.e. creep.travelTo(new RoomPosition(25, 25, ), {avoidHostileRooms: true})
> 
> If you get rid of the option then your never travel to a room that has a hostile weight which you may want to be able to do at some point.
> 
> @JeremyGagnier if you open the PR for the fix I'd be happy to help with a +1 for you.

@mebays Oh, you're right. I didn't see that map.findRoute call. Next time I'll read the code a bit more carefully... 🤦‍♂️

Yep, then I'll give a +1 too.

**Comment by JeremyGagnier** [comment]
@duckymirror @mebays thank you both for the replies. Here's the PR reopened if you would like to give +1's: #404
