### ISSUE TITLE
[Bug] Cache needs to be invalidated after a certain point to reevaluate blocked exits

### ISSUE THREAD

**Issue by alexanselmo** [ScreepsQuorum/screeps-quorum#439]
Exits can be temporarily blocked in the case of Novice zones and other potential obstructions. We need a way to invalidate the cache and reevaluate paths.

https://github.com/ScreepsQuorum/screeps-quorum/blob/f6868c56ef4ba77029b506aea840cc3bf9c31415/src/lib/map.js#L19-L33

**Comment by tedivm** [comment]
The cache automatically invalidates after 150 ticks (that's what the maxttl is for).

**Comment by alexanselmo** [comment]
Interesting, I was running into an issue where my creeps thought an exit was blocked, long after it had been unblocked. I'll dig in a little deeper and see where the true error lies.

**Comment by tedivm** [comment]
You may want to look at the costmatrix generation and caching code, as anything there would trickle up to the pathfinding layer.

**Comment by alexanselmo** [comment]
Ok, thanks. I'm going to close this issue until I can get a better understanding of where it went wrong.
